### ISSUE TITLE
Can I obtain SNP rs ids using CHR:POS or CHR:POS_A1_A2 column?

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [ldehoyos/twinSNP#1]

**Comment by ldehoyos** [comment]
Hi Mahantesh-Biradar,

Sure that is not problem, you can do it. The only thing you need to make sure is that the column 'snpID' in your database and the column 'input_snp' of your vector of SNPs to be matched have the same format. So, for example: 

If you want **CHR:POS** 

```
# Your database
> myDatabase$snpID
[1] "10:10001753"  "10:10001794"  "10:100023489" "10:100025128" ....

# Your SNPs of interest
> myVars$input_snp
[1]  "10:101671240" "10:101672887"
```

if you want **CHR:POS_A1_A2**
```
# Your database
> myDatabase$snpID
[1] "10:10001753_A_G"  "10:10001794_C_T"  "10:100023489_A_C" "10:100025128_T_G" ....

# Your SNPs of interest
> myVars$input_snp
[1]  "10:101671240_C_T" "10:101672887_A_G"
```

**Comment by Mahantesh-Biradar** [comment]
Thanks Idehoyos, 

I'm trying to install this package, but I seem to have some issue:

**library(devtools)
> install_github("ldehoyos/twinSNP")
Error: Failed to install 'unknown package' from GitHub:
  cannot open the connection
In addition: Warning messages:
1: In file(con, "wb") :
  cannot open file 'C:\Users\mahaan\AppData\Local\Temp\RtmpgvxGt7\file44c8176f510a': No such file or directory
2: In file(con, "wb") :
  cannot open file 'C:\Users\mahaan\AppData\Local\Temp\RtmpgvxGt7\file44c838a32f38': No such file or directory**
